apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spiffe-demo
  name: spiffe-demo
  namespace: spiffe-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: spiffe-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: spiffe-demo
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
            # Setup Git Configuration
            git config --global init.defaultBranch main
            git config --global user.name "RHTAS User"
            git config --global user.email "rhtas@redhat.com"
            git config --global commit.gpgsign true
            git config --global tag.gpgsign true
            git config --global gpg.x509.program gitsign
            git config --global gpg.format x509

            # Initialize cosign
            cosign initialize

            # Sleep
            while true; do sleep 5; done
        env:
        - name: PATH
          value: /wto/bin:/wto/bin/downloaded:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/tools/bin
        - name: SPIFFE_ENDPOINT_SOCKET
          value: /spiffe-workload-api/spire-agent.sock
        - name: COSIGN_OIDC_ISSUER
          value: https://oidc-discovery.rhtas.openshift.io
        - name: COSIGN_FULCIO_URL
          value: https://fulcio.apps.rhtas.openshift.io
        - name: TUF_URL
          value: https://tuf.apps.rhtas.openshift.io
        - name: COSIGN_REKOR_URL
          value: https://rekor.apps.rhtas.openshift.io
        - name: COSIGN_MIRROR
          value: https://tuf.apps.rhtas.openshift.io
        - name: COSIGN_ROOT
          value: https://tuf.apps.rhtas.openshift.io/root.json
        - name: COSIGN_CERTIFICATE_OIDC_ISSUER
          value: https://oidc-discovery.apps.rhtas.openshift.io
        - name: SIGSTORE_FULCIO_URL
          value: https://fulcio.apps.rhtas.openshift.io
        - name: SIGSTORE_OIDC_ISSUER
          value: https://oidc-discovery.apps.rhtas.openshift.io
        - name: SIGSTORE_REKOR_URL
          value: https://rekor.apps.rhtas.openshift.io
        - name: REKOR_REKOR_SERVER
          value: https://rekor.apps.rhtas.openshift.io
        - name: GITSIGN_OIDC_ISSUER
          value: https://oidc-discovery.apps.rhtas.openshift.io
        - name: GITSIGN_REKOR_URL
          value: https://rekor.apps.rhtas.openshift.io
        - name: GITSIGN_FULCIO_URL
          value: https://fulcio.apps.rhtas.openshift.io
        - name: GIT_AUTHOR_NAME
          value: "RHTAS User"
        - name: GIT_AUTHOR_EMAIL
          value: rhtas@redhat.com
        - name: COSIGN_YES
          value: "true"
        - name: OPENSHIFT_APPS_DOMAIN
          value: apps.rhtas.openshift.io
        image: registry.redhat.io/web-terminal/web-terminal-tooling-rhel8@sha256:f0a9e35023c83041e98fb18db0a740b6912d421f956cca0cad3e66bdfd6cf450
        imagePullPolicy: IfNotPresent
        name: spiffe-demo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/tools
          name: tools
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api/
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/bash
        - -c
        - mkdir -p /var/tools/bin && cp -vf /opt/app-root/src/clients/linux/cosign-amd64.gz /var/tools/bin/cosign.gz && cp -vf /opt/app-root/src/clients/linux/gitsign-amd64.gz /var/tools/bin/gitsign.gz
        image: quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-cg@sha256:5c7e83f13f9ba52c927bcb86abb5f9efa8ca4fe9ab7031709bde7f48829f6d0f
        imagePullPolicy: IfNotPresent
        name: rhtas-clis
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/tools
          name: tools
      - command:
        - /bin/bash
        - -c
        - mkdir -p /var/tools/bin && cp -vf /opt/app-root/src/clients/linux/rekor-cli-amd64.gz /var/tools/bin/rekor-cli.gz
        image: quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-re@sha256:d20c57b457650a025c225863462b2f9bf193ca35534dbf2cfcd9f6ab07a091b9
        imagePullPolicy: IfNotPresent
        name: rhtas-clis-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/tools
          name: tools
      - command:
        - /bin/bash
        - -c
        - mkdir -p /var/tools/bin && ls -l /var/tools/bin && gunzip -c /var/tools/bin/cosign.gz > /var/tools/bin/cosign && chmod +x /var/tools/bin/cosign && rm -f //var/tools/bin/cosign.gz && gunzip -c /var/tools/bin/gitsign.gz > /var/tools/bin/gitsign && chmod +x /var/tools/bin/gitsign && rm -f /var/tools/bin/gitsign.gz && gunzip -c /var/tools/bin/rekor-cli.gz > /var/tools/bin/rekor-cli && chmod +x /var/tools/bin/rekor-cli && rm -f /var/tools/bin/rekor-cli.gz
        image: registry.access.redhat.com/ubi9/toolbox@sha256:47d4891b3e744f5622a31bd21a42dd51358c43bbfd44860cc05c7b29cc520e66
        imagePullPolicy: IfNotPresent
        name: rhtas-clis-unzip
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/tools
          name: tools
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tools
      - csi:
          driver: csi.spiffe.io
          readOnly: true
        name: spiffe-workload-api
